### ISSUE TITLE
Can't get the result

### ISSUE THREAD

**Issue by CrisJk** [SharmisthaJat/RE-DS-Word-Attention-Models#4]
@SharmisthaJat 
Hi, sorry to disturb you, but I'm confused about the BGWA algorithm. I implement the algorithm by myself, but I can't get a good result(auc is low).  I just run your code but get the error message:

`  File "BGWA.py", line 130, in forward
    attention_values_sum = torch.sum(attention_exp,1).expand(gru.size(0), self.input_words, self.gru_layers*2)
RuntimeError: The expanded size of the tensor (82) must match the existing size (2000) at non-singleton dimension 1.  Target sizes: [2000, 82, 460].  Tensor sizes: [2000, 460]`

**Comment by SharmisthaJat** [comment]
Hi, 

This error message is new to me. Can you provide more information regarding the input and the full trace of the run?

**Comment by CrisJk** [comment]
I get this error by executing following script
 `python2 BGWA.py RE-DS-Word-Attention-Models/Codes/Preprocess train_final.p test_final.p dev_final.p Wv.p`

I don't know but I'm sorry if I made mistake about the python script.

**Comment by SharmisthaJat** [comment]
oh, some of these errors might be there if you are using any other version of PyTorch (some functions are not back-compatible with previous versions), please make sure you are using the same library versions as given in the Readme file, we have provided a requirements.txt file which matches the versions we used. For the older version of Pytorch, you might need to use a wheel or source install from GitHub. Let me know more information to diagnose since I have not encountered this error before.

**Comment by CrisJk** [comment]
My pip installed list is as following:
`
numpy==1.16.0
Pillow==5.4.1
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
sklearn==0.0
torch==1.0.0
torchvision==0.2.1
`
I have tried to install the torch 0.1.12.post2 as requirements.txt file but I'm failed. Maybe this is the problem. I would try it again when I have time.

Thank you for your help!

**Comment by SharmisthaJat** [comment]
Ok, let me know if there is any other issue. Goodluck :)
