### ISSUE TITLE
Question about GDS dataset

### ISSUE THREAD

**Issue by xiang-deng** [SharmisthaJat/RE-DS-Word-Attention-Models#6]
In the original Google Relation Extraction Corpus (https://github.com/google-research-datasets/relation-extraction-corpus), there are 5 relations: `place_of_birth`, `place_of_death`, `institution`, `degree` and `data_of_death`. But in the paper, the fifth relation of GDS is `NA`, how did you get the entity pairs for that relation. 
Also, the number of entity pairs in Table 2 doesn't match the number of lines in the original files, is there any other filtering applied?

**Comment by SharmisthaJat** [comment]
Hi, 

1) The NA relation comes from the entity pairs which have a negative label (by voting in original dataset) for any of the relation labels. 
2) The original file contains more entity-pairs, than the extended RE-DS dataset due to 2 reasons. (a) restrictions on the google search budget; (b) we wanted to build an almost balanced dataset for the evaluation of DS task, in the original dataset the number of entity-pairs in each relation are imbalanced.

Some of these points are described in details in the accompanying arxiv paper in Section 3. I hope this answers your questions. Let me know if you need more information.
